// ─── AUTH HELPERS ───
export function loadGSI(){return new Promise(r=>{if(document.getElementById("gsi"))return r();const s=document.createElement("script");s.id="gsi";s.src="https://accounts.google.com/gsi/client";s.onload=r;document.head.appendChild(s);});}
export function decJwt(t){try{return JSON.parse(atob(t.split(".")[1].replace(/-/g,"+").replace(/_/g,"/")));}catch{return null;}}
export function connectStrava(){const c=import.meta.env.VITE_STRAVA_CLIENT_ID;if(c)window.location.href=`https://www.strava.com/oauth/authorize?client_id=${c}&response_type=code&redirect_uri=${window.location.origin}&scope=read,activity:read&approval_prompt=auto`;}
export async function exchStrava(code){try{return await(await fetch("https://www.strava.com/oauth/token",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({client_id:import.meta.env.VITE_STRAVA_CLIENT_ID,client_secret:import.meta.env.VITE_STRAVA_CLIENT_SECRET,code,grant_type:"authorization_code"})})).json();}catch{return null;}}
export async function fetchStrava(token){try{const[a,b]=await Promise.all([fetch("https://www.strava.com/api/v3/athlete",{headers:{Authorization:`Bearer ${token}`}}),fetch("https://www.strava.com/api/v3/athlete/activities?per_page=10",{headers:{Authorization:`Bearer ${token}`}})]);const at=await a.json(),ac=await b.json();let st=null;if(at.id)try{st=await(await fetch(`https://www.strava.com/api/v3/athletes/${at.id}/stats`,{headers:{Authorization:`Bearer ${token}`}})).json();}catch{}const rc=Array.isArray(ac)?ac.slice(0,10).map(x=>({type:x.type,name:x.name,distance:(x.distance/1000).toFixed(1)+"km",duration:Math.round(x.moving_time/60)+"min",date:new Date(x.start_date_local).toLocaleDateString()})):[];return{name:`${at.firstname||""} ${at.lastname||""}`.trim(),city:at.city||"",recentActivities:rc,allTimeRuns:st?.all_run_totals?.count||0,allTimeRunDistance:st?.all_run_totals?.distance?(st.all_run_totals.distance/1000).toFixed(0)+"km":"0km",allTimeRides:st?.all_ride_totals?.count||0,allTimeRideDistance:st?.all_ride_totals?.distance?(st.all_ride_totals.distance/1000).toFixed(0)+"km":"0km"};}catch{return null;}}

// ─── GOOGLE CALENDAR ───
export function connectGCal(cb){const cid=import.meta.env.VITE_GOOGLE_CLIENT_ID;if(!cid)return;loadGSI().then(()=>{if(!window.google?.accounts?.oauth2)return;window.google.accounts.oauth2.initTokenClient({client_id:cid,scope:"https://www.googleapis.com/auth/calendar.events",callback:r=>{if(r.access_token)cb(r);}}).requestAccessToken();});}
export async function fetchGCal(token){try{const now=new Date().toISOString(),end=new Date(Date.now()+14*864e5).toISOString();const r=await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=${encodeURIComponent(now)}&timeMax=${encodeURIComponent(end)}&maxResults=30&singleEvents=true&orderBy=startTime`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();return(d.items||[]).map(e=>({title:e.summary||"",start:e.start?.dateTime||e.start?.date||"",end:e.end?.dateTime||e.end?.date||"",location:e.location||"",allDay:!!e.start?.date&&!e.start?.dateTime}));}catch{return null;}}
export async function addGCalEvent(token,title,desc,time){try{const s=new Date();const tl=(time||"").toLowerCase();if(tl.includes("tomorrow"))s.setDate(s.getDate()+1);if(tl.includes("tonight")||tl.includes("pm")){const m=tl.match(/(\d{1,2})\s*pm/);s.setHours(m?parseInt(m[1])+12:19,0,0);}if(tl.includes("am")){const m=tl.match(/(\d{1,2})\s*am/);if(m)s.setHours(parseInt(m[1]),0,0);}if(tl.includes("weekend")){s.setDate(s.getDate()+(6-s.getDay()+7)%7||7);s.setHours(10,0,0);}const e=new Date(s.getTime()+36e5);const tz=Intl.DateTimeFormat().resolvedOptions().timeZone;const r=await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({summary:title,description:desc||"From My Next Step",start:{dateTime:s.toISOString(),timeZone:tz},end:{dateTime:e.toISOString(),timeZone:tz}})});return r.ok;}catch{return false;}}
export async function addGCalRecurring(token,title,desc,schedule,days,time){try{
  const dayMap={sunday:"SU",monday:"MO",tuesday:"TU",wednesday:"WE",thursday:"TH",friday:"FR",saturday:"SA"};
  const tz=Intl.DateTimeFormat().resolvedOptions().timeZone;
  // Parse time field (e.g. "7am", "6:30pm", "14:00")
  const s=new Date();s.setHours(9,0,0,0);
  if(time){const tl=time.toLowerCase().trim();const pm=tl.match(/(\d{1,2})(?::(\d{2}))?\s*pm/);const am=tl.match(/(\d{1,2})(?::(\d{2}))?\s*am/);const h24=tl.match(/^(\d{1,2}):(\d{2})$/);if(pm)s.setHours(parseInt(pm[1])+(parseInt(pm[1])===12?0:12),parseInt(pm[2]||0),0);else if(am)s.setHours(parseInt(am[1])===12?0:parseInt(am[1]),parseInt(am[2]||0),0);else if(h24)s.setHours(parseInt(h24[1]),parseInt(h24[2]),0);}
  if(days&&days.length>0){const targetDay=["sunday","monday","tuesday","wednesday","thursday","friday","saturday"].indexOf(days[0].toLowerCase());if(targetDay>=0){while(s.getDay()!==targetDay)s.setDate(s.getDate()+1);}}
  const e=new Date(s.getTime()+36e5);
  // Build RRULE
  let rrule="";const freq=schedule?.toLowerCase()||"weekly";
  if(freq==="daily")rrule="RRULE:FREQ=DAILY";
  else if(freq==="biweekly")rrule="RRULE:FREQ=WEEKLY;INTERVAL=2";
  else if(freq==="monthly")rrule="RRULE:FREQ=MONTHLY";
  else rrule="RRULE:FREQ=WEEKLY";
  if(days&&days.length>0&&freq!=="daily"){const byDay=days.map(d=>dayMap[d.toLowerCase()]||"").filter(Boolean).join(",");if(byDay)rrule+=";BYDAY="+byDay;}
  const r=await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({summary:title,description:desc||"From My Next Step",start:{dateTime:s.toISOString(),timeZone:tz},end:{dateTime:e.toISOString(),timeZone:tz},recurrence:[rrule]})});
  return r.ok;}catch{return false;}}
